### ISSUE TITLE
Why `warn` instead of `error` for `comma-dangle`?

### ISSUE THREAD

**Issue by spl** [AuroraDigital/eslint-config-aurora#3]
First, thanks for this package! It has practically the same settings that I use.

I'm curious about your motivation to use `warn` instead of `error` in:

```js
'comma-dangle': ['warn', 'always-multiline']
```

**Comment by pfcodes** [comment]
When using `error` with ESLint a non-zero exit code is triggered and that will cause CI builds to fail. So if you do a CI deploy where you're missing a comma, the entire build fails and you have to fix it and then restart the entire process all over again. A missing comma just isn't that severe to justify it as being an error.

**Comment by spl** [comment]
Thanks for the explanation!

I can certainly sympathize with the frustration of having to restart a possibly time-consuming process for such a small thing. I guess I'm not clear on why `comma-dangle` gets special treatment over other rules.

Would you consider changing `warn` to `error`? In my case, I'd rather have the style completely specified to preserve consistency without any exceptions.

It's not a very big deal if you don't want to change it. I discovered yesterday that I can effectively turn all warnings into errors for CI by passing `--max-warnings 0` to `eslint`.

**Comment by pfcodes** [comment]
I know it's inconsistent but it also comes down to how things appear in the text editor as well. Recall that the primary point of this style is to make things more readable. Having a space before the parenthesis for the function name is unusual for languages I've ever used and as a result makes the code not as readable. This reduced readability is enough to show red in text editors.

I don't think a missing dangling comma should show red in text editors, distracting from higher priority issues as a result. You could make the argument that semicolons are errors and show red, but the error being shown is to _remove_ a character, not to add one. The opinionated change here is that semicolons add clutter and isn't good for readability.

Finally, the dangling comma is not there to make things more readable, it's there for to be convenient when making additions to a list. 

I think this is a good convention to follow: Errors for readability (highest priority items) and warnings for (mostly) everything else. Yes, this is inconsistent when it comes to CI and builds, but can be appreciated when text editing time it serves some purpose. 

The ESLint team made `warn` and `--max-warnings` for a reason. I think passing `--max-warnings 0` is the perfect compromise.

**Comment by spl** [comment]
Thanks for the well-thought-out comment. I appreciate the time you've given this issue, and I believe we've discussed it enough. I'll just respond with my thoughts on a few things you said before closing the issue.

> I know it's inconsistent but it also comes down to how things appear in the text editor as well. Recall that the primary point of this style is to make things more readable. Having a space before the parenthesis for the function name is unusual for languages I've ever used and as a result makes the code not as readable. This reduced readability is enough to show red in text editors.

Okay, I haven't seen that myself in the editors I use (mainly Vim). My motivation for the `{ "anonymous": "always", "named": "never", "asyncArrow": "always" }` style is that (a) named functions can easily be distinguished from unnamed functions and (b) the space after a named function can add superfluous horizontal length to a signature.

> Finally, the dangling comma is not there to make things more readable, it's there for to be convenient when making additions to a list.

I see. For me, the dangling comma is there to make the diffs more readable, not as a convenience for text entry. For example, the addition and subtraction of commas in `package.json` changes add a lot of noise, and I find this rather distracting during review.

> I think this is a good convention to follow: Errors for readability (highest priority items) and warnings for (mostly) everything else. Yes, this is inconsistent when it comes to CI and builds, but can be appreciated when text editing time it serves some purpose.

That's logical.

> The ESLint team made `warn` and `--max-warnings` for a reason. I think passing `--max-warnings 0` is the perfect compromise.

Agreed. Although, when I was looking at `standardx`, I didn't find a comparable flag to `--max-warnings`.

Thanks again!
